CREATE TABLE CLIENT (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CLIENT_ID VARCHAR (255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    COUNTRY_CODE VARCHAR(10) NOT NULL,
    LOAN_AMOUNT DECIMAL NOT NULL,
    PRIMARY KEY (ID)
);